#
# SPDX-FileCopyrightText: The uwuAOSP Project
# SPDX-License-Identifier: Apache-2.0
#

flag_value {
  package: "android.content.pm"
  name: "verification_service"
  state: DISABLED
  permission: READ_ONLY
}
