# PUI system icon overlays
PRODUCT_PACKAGES += \
    PuiSystemIcon_PUIThemeAPPDetailsIcon \
    PuiSystemIcon_PUIThemeAPPLockLauncherIcon \
    PuiSystemIcon_PUIThemeAluminumOSQuickPanelIcon \
    PuiSystemIcon_PUIThemeAluminumOSSettingIcon \
    PuiSystemIcon_PUIThemeAndroidLOGOIcon \
    PuiSystemIcon_PUIThemeAndroidQuickPanelIcon \
    PuiSystemIcon_PUIThemeAndroidStatIcon \
    PuiSystemIcon_PUIThemeBrightIcon \
    PuiSystemIcon_PUIThemeBubbleIcon \
    PuiSystemIcon_PUIThemeDarkThemeIcon \
    PuiSystemIcon_PUIThemeFingerprintIcon \
    PuiSystemIcon_PUIThemeLockScreenIcon \
    PuiSystemIcon_PUIThemeLunarisAOSPVolumeIcon \
    PuiSystemIcon_PUIThemeMIADBrightIcon \
    PuiSystemIcon_PUIThemeMIADStatIcon \
    PuiSystemIcon_PUIThemeNeotericOSBrightnessIcon \
    PuiSystemIcon_PUIThemeNoInternetWifiSignal \
    PuiSystemIcon_PUIThemeOneHandedIcon \
    PuiSystemIcon_PUIThemePowerPanelIconFramework \
    PuiSystemIcon_PUIThemePowerPanelIconSystemUI \
    PuiSystemIcon_PUIThemePrivacyIcon \
    PuiSystemIcon_PUIThemeSettingsPermissionsIcon \
    PuiSystemIcon_PUIThemeSignalIcon \
    PuiSystemIcon_PUIThemeSignalIconA16QPRBeta \
    PuiSystemIcon_PUIThemeSignalLOGOA16QPRBeta \
    PuiSystemIcon_PUIThemeSignalLogoIcon \
    PuiSystemIcon_PUIThemeSonyHDIcon \
    PuiSystemIcon_PUIThemeSysbarIconAOSP \
    PuiSystemIcon_PUIThemeSystemUILockScreenIcon \
    PuiSystemIcon_PUIThemeSystemUIQuickPanelIcon \
    PuiSystemIcon_PUIThemeSystemUIScreenRecordeIcon \
    PuiSystemIcon_PUIThemeSystemUIStatIcon \
    PuiSystemIcon_PUIThemeVolumePanelIcon \
    PuiSystemIcon_PUIThemedLineagesBrightIcon \
    PuiSystemIcon_PUIThemedLineagesQuickPanelIcon \
    PuiSystemIcon_PUIThemedLineagesRingIcon \
    PuiSystemIcon_PUIThemedLineagesSettingsIcon \
    PuiSystemIcon_PUIThemedLineagesUSBAndroidIcons \
    PuiSystemIcon_PUIThemedNX1SettingsIcon \
    PuiSystemIcon_PUIThemedQSIconCrd \
    PuiSystemIcon_PUIThemedSettingsIcon \
    PuiSystemIcon_PUIThemedSettingsIconBaklava \
    PuiSystemIcon_PUIThemedSettingsIconCrd \
    PuiSystemIcon_PUIThemedcrDroidHomeIcon \
    PuiSystemIcon_PUIThemeduwuAOSPSettingsIcon \
    PuiSystemIcon_PUIThemeuwuAOSPExpandSettingsIcon \
    PuiSystemIcon_PUIThemeuwuAOSPSystemUIIcon \
    PuiSystemIcon_PUIThmemBatteryIcon \
    PuiSystemIcon_PuiThemeMIADBatteryIcon
